name: 🧪 Maven Build & Test

on:
  # Trigger when code is pushed to main
  push:
    branches:
      - main
  # Allow manual run from GitHub Actions UI
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test with Maven
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java 21, adjust if needed)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Step 3: Build and run tests
      - name: Build with Maven
        run: mvn -B clean verify

      # Step 4: Upload test reports (optional but useful)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
