name: 🧪 Backend Maven Build & Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-build-test:
    name: Build & Test (backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and run Maven tests
        run: mvn -B clean verify
        working-directory: backend

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: backend/target/surefire-reports/
